version: 2

.cargo: &cargo
  steps:
    - checkout
    - run:
        name: Cargo test
        command: |
          cargo test -vv

jobs:
  cuda10.0-ubuntu18.04:
    <<: *cargo
    docker:
      - image: registry.gitlab.com/rust-cuda/container:cuda10.0-ubuntu18.04

workflows:
  version: 2
  tests:
    jobs:
      - cuda10.0-ubuntu18.04
