[package]
name = "cuda-runtime-sys"
version = "0.2.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]
edition = "2018"

build = "build.rs"
links = "cuda"

description   = "Rust binding to CUDA Driver/Runtime APIs"
documentation = "https://docs.rs/cuda-sys/"
repository    = "https://github.com/termoshtt/accel"
keywords      = ["GPGPU", "CUDA", "ffi"]
license       = "MIT"
readme        = "README.md"
categories    = []

[build-dependencies]
glob = "0.3.0"
